# Generated by Django 3.1.4 on 2021-01-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('力量', '力量'), ('健身操', '健身操'), ('椭圆机', '椭圆机'), ('散步', '散步')], max_length=100)),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='卡路里')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('工作', '工作'), ('学习', '学习'), ('娱乐', '娱乐'), ('健康', '健康')], max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('health', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event_tracker.eventhealth')),
            ],
        ),
    ]
